<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yml</string>
		<string>ansible</string>
	</array>
	<key>name</key>
	<string>Ansible</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#escape</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#text</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#task</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#parameter</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#caption</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#illegal</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bool</key>
		<dict>
			<key>match</key>
			<string>\b(yes|no|true|false|True|False)\b</string>
			<key>name</key>
			<string>entity.other.inherited-class.ansible</string>
		</dict>
		<key>caption</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.ansible</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.tag.ansible</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ansible</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(-? *[^{}] +)(name:)\ +(.*)</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>(\ +|^)#.*</string>
			<key>name</key>
			<string>comment.line.yaml-tmlanguage</string>
		</dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>(\\[tn"'0-9])</string>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>^\t+|^\s*\}</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized.yaml-tmlanguage</string>
		</dict>
		<key>includeOrHandler</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.tag.ansible</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ansible</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(include:|register:)\ +(.*)</string>
		</dict>
		<key>list</key>
		<dict>
			<key>match</key>
			<string>\s*-\s*[.+\w0-9_-]+$</string>
			<key>name</key>
			<string>support.constant.ansible</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\b\-?\d+\b</string>
			<key>name</key>
			<string>constant.numeric.ansible</string>
		</dict>
		<key>parameter</key>
		<dict>
			<key>begin</key>
			<string>\b(\w+)=</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\"|\')?(\s|^\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bool</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>constant.other.ansible</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(\"|\')</string>
			<key>end</key>
			<string>\1|^\s*$</string>
			<key>name</key>
			<string>variable.parameter.ansible</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<key>tag</key>
		<dict>
			<key>match</key>
			<string>\ *[\w_-]+[:]</string>
			<key>name</key>
			<string>keyword.other.tag.ansible</string>
		</dict>
		<key>task</key>
		<dict>
			<key>begin</key>
			<string>^ *</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#caption</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#includeOrHandler</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bool</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_bash</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>begin</key>
			<string>\$?\{\{ *</string>
			<key>end</key>
			<string>\s*\}\}</string>
			<key>name</key>
			<string>storage.type.ansible</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>variable_bash</key>
		<dict>
			<key>match</key>
			<string>\$\{?\w+\}?</string>
			<key>name</key>
			<string>entity.other.inherited-class.ansible</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ansible</string>
	<key>uuid</key>
	<string>bdbdd0f8-6808-4d09-a51a-c2d8b7aec0a1</string>
</dict>
</plist>
